"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.aiService = void 0;
const env_1 = require("../config/env");
// We will reuse env.openAiKey as the OpenRouter key
const OPENROUTER_KEY = env_1.env.openAiKey;
// Simple local heuristic fallback when OpenRouter is unavailable or quota is exhausted
function fallbackAnalysis(sanitizedLog) {
    const lower = sanitizedLog.toLowerCase();
    let issueType = "General Error";
    let rootCause = "The system encountered an error as shown in the log snippet.";
    let suggestedFix = "Review the stack trace and configuration around the failing component, then rerun with additional logging.";
    let severity = "minor";
    const insights = [];
    if (lower.includes("exception") || lower.includes("stack trace")) {
        issueType = "Application Exception";
        rootCause =
            "The log shows an unhandled exception propagating through the application stack.";
        suggestedFix =
            "Identify the origin of the exception in the stack trace, add proper error handling, and validate input data.";
        severity = "major";
    }
    if (lower.includes("timeout") || lower.includes("timed out")) {
        issueType = "Timeout / Performance Issue";
        rootCause =
            "An operation exceeded its time limit, indicating a slow dependency or inefficient query.";
        suggestedFix =
            "Profile the slow operation, add proper timeouts and retries, and optimize database or network calls.";
        severity = "major";
    }
    if (lower.includes("connection refused") || lower.includes("econnrefused")) {
        issueType = "Network / Service Connectivity";
        rootCause =
            "The application could not reach a required downstream service or database.";
        suggestedFix =
            "Check service URLs, ports, firewall rules, and ensure the target service is healthy and reachable.";
        severity = "critical";
    }
    if (lower.includes("permission denied") ||
        lower.includes("unauthorized") ||
        lower.includes("forbidden")) {
        issueType = "Authentication / Authorization";
        rootCause =
            "The request or process does not have the required permissions or credentials.";
        suggestedFix =
            "Verify credentials, tokens, and role permissions; update IAM or application config accordingly.";
        severity = "major";
    }
    if (lower.includes("disk full") || lower.includes("no space left")) {
        issueType = "Infrastructure / Disk Space";
        rootCause = "The host machine has insufficient disk space for the operation.";
        suggestedFix =
            "Free disk space, rotate logs, or increase disk capacity. Add monitoring and alerts for disk usage.";
        severity = "critical";
    }
    insights.push("This analysis was generated by the built-in heuristic engine because the OpenRouter API was unavailable or returned an error.");
    return { issueType, rootCause, suggestedFix, severity, insights };
}
const systemPrompt = `
You are an AI bug tracker assistant that analyzes sanitized log files. 
Respond ONLY with valid JSON matching this schema:
{
  "issueType": string,
  "rootCause": string,
  "suggestedFix": string,
  "severity": "critical" | "major" | "minor" | "info",
  "insights": string[]
}
`.trim();
exports.aiService = {
    async analyzeLog(sanitizedLog) {
        // If no OpenRouter key is configured, use local fallback
        if (!OPENROUTER_KEY) {
            return fallbackAnalysis(sanitizedLog);
        }
        try {
            // Using Node 18+ global fetch
            const response = await fetch("https://openrouter.ai/api/v1/chat/completions", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json",
                    Authorization: `Bearer ${OPENROUTER_KEY}`,
                    // Recommended by OpenRouter docs (use anything descriptive for local dev)
                    "HTTP-Referer": "http://localhost:5173",
                    "X-Title": "AI Bug Tracker",
                },
                body: JSON.stringify({
                    model: "openai/gpt-4o-mini", // or any other OpenRouter-supported model
                    messages: [
                        {
                            role: "system",
                            content: systemPrompt,
                        },
                        {
                            role: "user",
                            content: `Sanitized Log:\n"""${sanitizedLog.slice(0, 5000)}"""`,
                        },
                    ],
                    temperature: 0.2,
                }),
            });
            if (!response.ok) {
                const text = await response.text();
                console.error("OpenRouter error:", response.status, text);
                return fallbackAnalysis(sanitizedLog);
            }
            const data = await response.json();
            const content = data.choices?.[0]?.message?.content ?? undefined;
            if (!content) {
                throw new Error("OpenRouter response missing content");
            }
            // Model is instructed to return JSON only
            const parsed = JSON.parse(content);
            return parsed;
        }
        catch (err) {
            console.error("OpenRouter call failed, using fallback:", err?.message);
            return fallbackAnalysis(sanitizedLog);
        }
    },
};
//# sourceMappingURL=aiService.js.map